use heapless::{String, Vec};
use serde::{Deserialize, Serialize};
use crate::policy_config::PolicyConfig;

// Struct defining expected typed parameters to avoid dynamic heap allocations
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ActionParameters {
    pub velocity: Option<f64>,
    pub angle: Option<f64>,
    pub ignore_safety: Option<bool>,
}

// Represents an action generated by the local AI agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentAction {
    pub tool_name: String<32>,
    pub target_hardware: String<32>,
    pub parameters: ActionParameters,
}

// Represents the outcome evaluated by the physical guardrails
#[derive(Debug)]
pub enum SafetyDecision {
    Allow,
    Block(String<256>),
    Corrected(AgentAction), // Proactively steers away from catastrophic failure
}

// Mock representation of the robot's current physical state
pub struct SystemState {
    pub current_velocity: f64,
    pub previous_velocity: f64,
    pub proximity_sensor_distance: f64,
    // Statistical tracking for anomaly detection
    pub velocity_history_count: u64,
    pub velocity_mean: f64,
    pub velocity_m2: f64, // Sum of squares of differences from the mean
}

impl SystemState {
    /// Initializes the system state and pre-fills the history buffer
    pub fn new(initial_velocity: f64, initial_proximity: f64) -> Self {
        Self {
            current_velocity: initial_velocity,
            previous_velocity: initial_velocity,
            proximity_sensor_distance: initial_proximity,
            velocity_history_count: 1,
            velocity_mean: initial_velocity,
            velocity_m2: 0.0,
        }
    }

    /// Updates the state by pushing the current reading into history, then applying the new reading.
    /// This uses Welford's online algorithm to update mean and variance.
    pub fn update_state(&mut self, new_velocity: f64, new_proximity: f64) {
        self.previous_velocity = self.current_velocity;
        self.current_velocity = new_velocity;
        self.proximity_sensor_distance = new_proximity;

        // Welford's online algorithm
        self.velocity_history_count += 1;
        let delta = new_velocity - self.velocity_mean;
        self.velocity_mean += delta / self.velocity_history_count as f64;
        let delta2 = new_velocity - self.velocity_mean;
        self.velocity_m2 += delta * delta2;
    }

    pub fn velocity_variance(&self) -> f64 {
        if self.velocity_history_count < 2 {
            0.0
        } else {
            self.velocity_m2 / (self.velocity_history_count - 1) as f64
        }
    }

    pub fn velocity_std_dev(&self) -> f64 {
        self.velocity_variance().sqrt()
    }
}

// A trait defining a control-theoretic guardrail
pub trait PhysicalGuardrail {
    fn evaluate(&self, policy: &PolicyConfig, current_state: &SystemState, action: &AgentAction) -> SafetyDecision;
}

// --- The Core Policy Engine ---

pub struct AgentArmorEdge<'a, const MAX_GUARDRAILS: usize = 8> {
    guardrails: Vec<&'a dyn PhysicalGuardrail, MAX_GUARDRAILS>,
}

impl<'a, const MAX_GUARDRAILS: usize> AgentArmorEdge<'a, MAX_GUARDRAILS> {
    pub fn new() -> Self {
        Self { guardrails: Vec::new() }
    }

    pub fn register_guardrail(&mut self, guardrail: &'a dyn PhysicalGuardrail) {
        let _ = self.guardrails.push(guardrail);
    }

    // Evaluates the agent's intent in real-time against all loaded guardrails
    pub fn enforce(&self, policy: &PolicyConfig, state: &SystemState, action: &AgentAction) -> SafetyDecision {
        let mut current_action = action.clone();
        let mut was_corrected = false;

        for guardrail in &self.guardrails {
            match guardrail.evaluate(policy, state, &current_action) {
                SafetyDecision::Block(reason) => return SafetyDecision::Block(reason),
                SafetyDecision::Corrected(corrected_action) => {
                    current_action = corrected_action;
                    was_corrected = true;
                }
                SafetyDecision::Allow => {}
            }
        }

        if was_corrected { SafetyDecision::Corrected(current_action) } else { SafetyDecision::Allow }
    }
}